apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cloudwatch-agent.fullname" . }}
  labels:
    app: {{ template "cloudwatch-agent.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  # Configuration is in Json format. No matter what configure change you make,
  # please keep the Json blob valid.
  cwagentconfig.json: |
    {
      "agent": {
        "region": "{{ .Values.awsRegion }}"
      },
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "{{ .Values.eksClusterName }}",
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    }